---
spring:

  cloud:

    stream:

      function:
        definition: workorderEventsDistribution

      bindings:
        workorder-events-distribution-in-0:
          destination: ${node.current}.workorder-events
          group: workorder-events-distribution
        workorder-events-distribution-cloud-out-0:
          destination: ${node.current}.distribution-cloud

