
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.cloud: DEBUG
    org.springframework.cloud.stream: INFO
    org.springframework.web: INFO
    io.pivotal.dmfrey: DEBUG

node:
  current: local
  available: local, cloud, node-17, node-34

spring:

  jackson:
    serialization:
      write_dates_as_timestamps: false

  cloud:
    stream:
      bindings:
        workorder-events-output:
          destination: ${node.current}.workorder-events
          contentType: application/json
          producer:
            headerMode: headers
        workorder-events-input:
          destination: ${node.current}.workorder-events
          group: workorder-events-stream
          contentType: application/json
          consumer:
            headerMode: headers
      kafka:
        binder:
          brokers: ["localhost:9092"]
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
          bindings:
            workorder-events-input:
              consumer.application-id: ${node.current}.event-stream-demo
            workorder-events-by-id:
              consumer:
                materializedAs: ${node.current}.workorder-events-by-id

#Actuator
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true
