---
spring:
  profiles: node

  cloud:
    stream:
      function:
        definition: workorderEvents;workorderEventsDistribution
      functions:
        workorderEventsDistribution:
          applicationId: ${node.current}.event-stream-demo.distribution-cloud
      source: workorder-events;workorder-events-distribution-cloud
      bindings:
        workorderEventsDistribution-in-0:
          destination: ${node.current}.workorder-events
        workorder-events-distribution-cloud-out-0:
          destination: ${node.current}.distribution-cloud

