---
spring:
  profiles: cloud

  cloud:
    stream:
      function:
        definition: workorderEvents;workorderEventsDistribution
      functions:
        workorderEventsDistribution:
          applicationId: ${node.current}.event-stream-demo.distribution-splitter
      source: workorder-events;workorder-events-distribution-cloud;workorder-events-distribution-local;workorder-events-distribution-node-17;workorder-events-distribution-node-34
      bindings:
        workorderEventsDistribution-in-0:
          destination: ${node.current}.workorder-events
        workorder-events-distribution-cloud-out-0:
          destination: ${node.current}.distribution-cloud
        workorder-events-distribution-local-out-0:
          destination: ${node.current}.distribution-local
        workorder-events-distribution-node-17-out-0:
          destination: ${node.current}.distribution-node-17
        workorder-events-distribution-node-34-out-0:
          destination: ${node.current}.distribution-node-34
#      kafka:
#        streams:
#          bindings:
#            workorderEventsDistribution-in-0:
#              consumer.application-id: ${node.current}.event-stream-demo.distribution-splitter

node:
  current: cloud

server:
  port: 9090

