---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dmfrey/debian-openjdk11
    tag: latest

inputs:
  - name: src-repo

outputs:
  - name: artifacts

caches:
  - path: .m2/

params:
  BUILD_CMD: ./mvnw package

run:
  path: src-repo/ci/scripts/build-and-publish.sh