apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: node-17
  labels:
    app: event-stream-demo
  name: event-stream-demo
spec:
  ports:
  - name: 9017-8080
    port: 9017
    protocol: TCP
    targetPort: 8080
  selector:
    app: event-stream-demo
  type: ClusterIP
status:
  loadBalancer: {}
