apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: cloud
  labels:
    app: event-stream-demo
  name: event-stream-demo
spec:
  ports:
  - name: 9090-8080
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: event-stream-demo
  type: ClusterIP
status:
  loadBalancer: {}
