resources:

  - name: repo
    type: git
    source:
      uri: {{git_repo_uri}}
      branch: master

jobs:
  - name: build-and-publish
    plan:
      - get: src-repo
        resource: repo
        trigger: true

      - task: build and publish with maven
        file: src-repo/ci/tasks/build-and-publish.yml
